# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 09:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=40)),
                ('anio', models.PositiveSmallIntegerField(default=0, verbose_name='año')),
                ('numero_periodo', models.PositiveSmallIntegerField(default=0)),
                ('infoadicional', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=50)),
                ('titulo', models.CharField(default='', max_length=50)),
                ('duracion', models.SmallIntegerField(default=0)),
                ('unidad_duracion', models.CharField(choices=[('A', 'Año/s'), ('D', 'Día/s'), ('M', 'Mes/es')], default='A', max_length=1)),
                ('acepta_licencias', models.BooleanField(default=False)),
                ('cantidad_minima_pagos', models.PositiveSmallIntegerField(default=0)),
                ('cantidad_max_examenes_por_inscripcion', models.PositiveSmallIntegerField(default=0)),
                ('abreviatura', models.CharField(blank=True, max_length=8)),
                ('vigente', models.BooleanField(default=True)),
                ('infoadicional', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Contenidos',
            },
        ),
        migrations.CreateModel(
            name='DerechoExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academias.Asignatura')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academias.Contenido')),
            ],
            options={
                'verbose_name_plural': 'Derecho a Examenes',
                'verbose_name': 'Derecho A Examen',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=80)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('web', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contacto', models.CharField(blank=True, max_length=50)),
                ('infoadicional', models.CharField(blank=True, max_length=150)),
                ('abreviatura', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota', models.PositiveSmallIntegerField(default=0)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Concepto')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academias.Contenido')),
            ],
        ),
        migrations.AddField(
            model_name='derechoexamen',
            name='planpago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academias.PlanPago'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academias.Institucion'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Modalidad'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Tipo'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academias.Contenido'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='nombre_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Nombre_Periodo'),
        ),
    ]
