# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 09:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        ('academias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(choices=[('D', 'DNI'), ('C', 'CEDULA')], default='D', max_length=1)),
                ('numero_documento', models.PositiveIntegerField(unique=True)),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=25)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Localidad')),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='EstadoInscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2017, 5, 20, 9, 3, 32, 89790, tzinfo=utc))),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2017, 5, 20, 9, 3, 32, 88002, tzinfo=utc))),
                ('nota', models.PositiveSmallIntegerField(default=0)),
                ('equivalencia', models.BooleanField(default=False)),
                ('aprobado', models.BooleanField(default=False)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academias.Asignatura')),
            ],
            options={
                'verbose_name_plural': 'Examenes',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(blank=True, max_length=15)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academias.Contenido')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=datetime.datetime(2017, 5, 20, 9, 3, 32, 89182, tzinfo=utc))),
                ('numero_comprobante', models.CharField(max_length=15)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=6)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Inscripcion')),
                ('plan_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academias.PlanPago')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.AddField(
            model_name='examen',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Inscripcion'),
        ),
        migrations.AddField(
            model_name='estadoinscripcion',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Inscripcion'),
        ),
    ]
