# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 14:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='estadoinscripcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2017, 5, 20, 14, 37, 47, 478506, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2017, 5, 20, 14, 37, 47, 476743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2017, 5, 20, 14, 37, 47, 477909, tzinfo=utc)),
        ),
    ]
